# Generated by Django 4.2.17 on 2025-01-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_profile_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='langage',
        ),
    ]
