# Generated by Django 5.0.7 on 2024-07-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtubeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('follower', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video_petit_format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('videoId', models.URLField()),
                ('thumbnails', models.URLField()),
                ('description', models.TextField()),
                ('programingLangage', models.CharField(max_length=100)),
                ('accountUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.youtubeur')),
            ],
        ),
        migrations.CreateModel(
            name='Video_long_format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('videoId', models.URLField()),
                ('thumbnails', models.URLField()),
                ('description', models.TextField()),
                ('programingLangage', models.CharField(max_length=100)),
                ('accountUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.youtubeur')),
            ],
        ),
        migrations.CreateModel(
            name='Video_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_video', models.URLField()),
                ('programmingLangage', models.CharField(max_length=100)),
                ('account_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.youtubeur')),
            ],
        ),
    ]
