# Generated by Django 4.2.17 on 2025-01-06 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.RemoveField(
            model_name='video_long_format',
            name='accountUser',
        ),
        migrations.RemoveField(
            model_name='video_petit_format',
            name='accountUser',
        ),
        migrations.DeleteModel(
            name='Video_list',
        ),
        migrations.DeleteModel(
            name='Video_long_format',
        ),
        migrations.DeleteModel(
            name='Video_petit_format',
        ),
        migrations.DeleteModel(
            name='Youtubeur',
        ),
    ]
